### PR TITLE
Case sensitive authorization method. Fixes #561

### LINKED ISSUE #561: UserNamePassword authentication should be case sensitive
Currently the doAuthentication method in UserNamePassword class is transforming the userid to lowercase:

```
credentials => {
        val userId = credentials._1.toLowerCase
        val password = credentials._2
```
If you are working with databases which care of lower and upper case (for instance PostgreSQL) the auth method will not work properly

### PR DESCRIPTION
**Pull request by albertostratio**
Get rid of toLowerCase method to make the authentication method case sensitive

### CODE REVIEW

**Comment by mjrussell** [comment]
How would this work for email based username password authorization? 

Emails should be case insensitive while I can see having case sensitive username support would be nice. Maybe it should be in a property inside the config file, similar to the username length and other fields

**Comment by albertostratio** [comment]
I agree, email should work as it was working before whereas username should be case sensitive.

Not sure if this configuration should be configurable though. I think this is a feature that everybody should want.

For instance, testing our current application our QAs create a new user with his first letter capitalized, it was stored with the first letter capitalize in our database but after SecureSocial was converting the string to lowercase we were not able to find the user in the DB and the user can not log in the application.

**Comment by jaliss** [comment]
I think usernames should not be case sensitive.  Why would we want them case sensitive?

**Comment by jaliss** [comment]
I'm closing this for now, please re-open if you need to discuss this further but I don't see why usernames would need to be case sensitive.

**Pull request closed without merging**
