### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by jtjeferreira**
build is passing :heavy_check_mark:  ~unfortunately the build for 2.11 is failing, will have a look in another PR~

### CODE REVIEW

**Comment by jtjeferreira** [comment]
closing and reopening

**Comment by jaliss** [comment]
@jtjeferreira this looks good, could you update to Scala `2.12.6` in the yml file and in `project/Common.scala`?

**Comment by jtjeferreira** [comment]
@jaliss done!

**Comment by jaliss** [comment]
thanks @jtjeferreira!

**Pull request merged**
